---
title: "SciPy"
subtitle: "Lecture 08"
author: "Dr. Colin Rundel"
footer: "Sta 663 - Spring 2025"
format:
  revealjs:
    theme: slides.scss
    transition: fade
    slide-number: true
    self-contained: true
execute:
  echo: true
  warning: true
  fig-width: 6
  fig-height: 4
  fig-dpi: 150
---



```{python setup}
#| include: false
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

plt.rcParams['figure.figsize'] = (6, 4)
plt.rcParams['figure.dpi'] = 150

np.set_printoptions(
  linewidth=100,
  precision=5, suppress=True
)

%xmode minimal
```

## What is SciPy

> Fundamental algorithms for scientific computing in Python

::: {.small}
| Subpackage    | Description                                           |   | Subpackage    | Description            
|:--------------|:------------------------------------------------------|---|:--------------|:-------------------------------------------
| `cluster`     | Clustering algorithms                                 |   | `odr`         | Orthogonal distance regression       
| `constants`   | Physical and mathematical constants                   |   | `optimize`    | Optimization and root-finding routines
| `fftpack`     | Fast Fourier Transform routines                       |   | `signal`      | Signal processing    
| `integrate`   | Integration and ordinary differential equation solvers|   | `sparse`      | Sparse matrices and associated routines
| `interpolate` | Interpolation and smoothing splines                   |   | `spatial`     | Spatial data structures and algorithms
| `io`          | Input and Output                                      |   | `special`     | Special functions
| `linalg`      | Linear algebra                                        |   | `stats`       | Statistical distributions and functions
| `ndimage`     | N-dimensional image processing                        |   | &nbsp;        | &nbsp;

:::


## SciPy vs NumPy

> In an ideal world, NumPy would contain nothing but the array data type and the most basic operations: indexing, sorting, reshaping, basic elementwise functions, etc. All numerical code would reside in SciPy. However, one of NumPy's important goals is compatibility, so NumPy tries to retain all features supported by either of its predecessors. Thus, NumPy contains some linear algebra functions and Fourier transforms, even though these more properly belong in SciPy. In any case, SciPy contains more fully-featured versions of the linear algebra modules, as well as many other numerical algorithms. If you are doing scientific computing with Python, you should probably install both NumPy and SciPy. Most new features belong in SciPy rather than NumPy.

::: {.aside}
From [scipy.org/faq/](https://scipy.org/faq/)
:::


# Example 1 <br/> k-means clustering

## Data

::: {.small}
```{python}
rng = np.random.default_rng(seed = 1234)
cl1 = rng.multivariate_normal([-2,-2], [[1,-0.5],[-0.5,1]], size=100)
cl2 = rng.multivariate_normal([1,0], [[1,0],[0,1]], size=150)
cl3 = rng.multivariate_normal([3,2], [[1,-0.7],[-0.7,1]], size=200)
pts = np.concatenate((cl1,cl2,cl3))
```
:::

. . .

```{python}
#| echo: false
#| fig-align: center
plt.figure(figsize=(4.5, 2.75))
plt.scatter(cl1[:,0], cl1[:,1], c="r", marker = ".", s=10)
plt.scatter(cl2[:,0], cl2[:,1], c="b", marker = "*", s=10)
plt.scatter(cl3[:,0], cl3[:,1], c="c", marker = "D", s=10)
plt.show()
```

## k-means clustering

::: {.xsmall}
```{python}
from scipy.cluster.vq import kmeans
ctr, dist = kmeans(pts, 3)
```
:::

:::: {.columns .xsmall}
::: {.column width='50%'}
```{python}
ctr
```
```{python}
dist
```
:::

::: {.column width='50%' .fragment}
```{python}
cl1.mean(axis=0)
```
```{python}
cl2.mean(axis=0)
```
```{python}
cl3.mean(axis=0)
```
:::
::::

. . .

```{python}
#| echo: false
#| fig-align: center
plt.figure(figsize=(4, 2))
plt.scatter(cl1[:,0], cl1[:,1], c="r", marker = ".", s=10)
plt.scatter(cl2[:,0], cl2[:,1], c="b", marker = "*", s=10)
plt.scatter(cl3[:,0], cl3[:,1], c="c", marker = "D", s=10)
plt.scatter(ctr[:,0], ctr[:,1], c="k", marker = ".", s = 250, linewidths=3.5)
plt.show()
```



## k-means distortion plot

> The mean (non-squared) Euclidean distance between the observations passed and the centroids generated.

::: {.xsmall}
```{python}
ks = range(1,8)
dists = [kmeans(pts, k)[1] for k in ks]
```
```{python}
np.array(dists).reshape(-1)
```

```{python}
#| echo: false
#| fig-align: center
plt.figure(figsize=(4., 2.5))
p = plt.plot(ks, dists, "-ok")
plt.show()
```
:::


## Assigning new points with vq()

Once we have centroids from `kmeans()`, we can assign new points to clusters using `vq()` (vector quantization).

::: {.xsmall}
```{python}
from scipy.cluster.vq import vq

new_pts = np.array([[0, 0], [-3, -3], [4, 3]])
labels, dists = vq(new_pts, ctr)
```
:::

::: {.columns .xsmall}
::: {.column}
```{python}
labels
```
```{python}
dists
```
:::
::: {.column .fragment}
```{python}
#| echo: false
#| fig-align: center
plt.figure(figsize=(4.5, 2.75))
plt.scatter(pts[:,0], pts[:,1], c="gray", alpha=0.3, s=10)
plt.scatter(ctr[:,0], ctr[:,1], c="k", marker=".", s=250, linewidths=3.5)
colors = ["c", "b", "r"]
for i, pt in enumerate(new_pts):
    plt.scatter(pt[0], pt[1], c=colors[labels[i]], marker="s", s=100, edgecolors="k")
plt.show()
```
:::
:::




# Example 2 <br/> Numerical integration

## Basic functions

For general numeric integration in 1D we use `scipy.integrate.quad()`, which takes as arguments: the function to be integrated and then the lower and upper bounds of the integral.

::: {.small}
```{python}
from scipy.integrate import quad
```

```{python}
quad(lambda x: x, 0, 1)
```
:::

. . .

::: {.small}
```{python}
quad(np.sin, 0, np.pi)
```
:::

. . .

::: {.small}
```{python}
quad(np.sin, 0, 2*np.pi)
```
:::

. . .

::: {.small}
```{python}
quad(np.exp, 0, 1)
```
:::


## Normal PDF

The PDF for a normal distribution is given by,

$$ f(x) = \frac{1}{\sigma \sqrt{2 \pi}} \exp\left(-\frac{1}{2} \left(\frac{x-\mu}{\sigma}\right)^2  \right) $$


::: {.small}
```{python}
def norm_pdf(x, μ, σ):
  return (1/(σ * np.sqrt(2*np.pi))) * np.exp(-0.5 * ((x - μ)/σ)**2)
```
:::

. . .

::: {.small}
```{python}
norm_pdf(0, 0, 1)
```
```{python}
norm_pdf(np.inf, 0, 1)
```
```{python}
norm_pdf(-np.inf, 0, 1)
```
:::

## Checking the PDF

We can check that we've implemented a valid pdf by integrating from $-\infty$ to $\infty$,

. . .

::: {.small}
```{python}
#| error: true
quad(norm_pdf, -np.inf, np.inf)
```
:::

. . .

::: {.small}
```{python}
quad(lambda x: norm_pdf(x, 0, 1), -np.inf, np.inf)
```
:::

. . .

::: {.small}
```{python}
quad(lambda x: norm_pdf(x, 17, 12), -np.inf, np.inf)
```
:::


## Truncated normal PDF

$$
f(x) = \begin{cases}
\frac{c}{\sigma \sqrt{2 \pi}} \exp\left(-\frac{1}{2} \left(\frac{x-\mu}{\sigma}\right)^2  \right), & \text{for } a \leq x \leq b \\
0,                                            & \text{otherwise.} \\
\end{cases}
$$

::: {.small}
```{python}
def trunc_norm_pdf(x, μ=0, σ=1, a=-np.inf, b=np.inf):
  if (b < a):
      raise ValueError("b must be greater than a")

  x = np.asarray(x)
  scalar_input = x.ndim == 0
  x = np.atleast_1d(x)

  full_pdf = (1/(σ * np.sqrt(2*np.pi))) * np.exp(-0.5 * ((x - μ)/σ)**2)
  full_pdf[(x < a) | (x > b)] = 0

  return full_pdf[0] if scalar_input else full_pdf
```
:::


## Testing trunc_norm_pdf


::: {.small}
```{python}
trunc_norm_pdf(0, a=-1, b=1)
```
```{python}
trunc_norm_pdf(2, a=-1, b=1)
```
```{python}
trunc_norm_pdf(-2, a=-1, b=1)
```
```{python}
trunc_norm_pdf([-2,1,0,1,2], a=-1, b=1)
```
:::

. . .

::: {.small}
```{python}
quad(lambda x: trunc_norm_pdf(x, a=-1, b=1), -np.inf, np.inf)
```
```{python}
quad(lambda x: trunc_norm_pdf(x, a=-3, b=3), -np.inf, np.inf)
```
:::


## Fixing trunc_norm_pdf

::: {.small}
```{python}
def trunc_norm_pdf(x, μ=0, σ=1, a=-np.inf, b=np.inf):
  if (b < a):
      raise ValueError("b must be greater than a")

  x = np.asarray(x)
  scalar_input = x.ndim == 0
  x = np.atleast_1d(x)

  nc = 1 / quad(lambda x: norm_pdf(x, μ, σ), a, b)[0]

  full_pdf = nc * (1/(σ * np.sqrt(2*np.pi))) * np.exp(-0.5 * ((x - μ)/σ)**2)
  full_pdf[(x < a) | (x > b)] = 0

  return full_pdf[0] if scalar_input else full_pdf
```
:::

##

::: {.small}
```{python}
trunc_norm_pdf(0, a=-1, b=1)
```
```{python}
trunc_norm_pdf(2, a=-1, b=1)
```
```{python}
trunc_norm_pdf(-2, a=-1, b=1)
```
```{python}
trunc_norm_pdf([-2,1,0,1,2], a=-1, b=1)
```
:::

. . .

::: {.small}
```{python}
quad(lambda x: trunc_norm_pdf(x, a=-1, b=1), -np.inf, np.inf)
```
```{python}
quad(lambda x: trunc_norm_pdf(x, a=-3, b=3), -np.inf, np.inf)
```
:::


## Multivariate normal

$$
f(\bf{x}) = \det{(2\pi\Sigma)}^{-1/2} \exp{\left(-\frac{1}{2} (\bf{x}-\mu)^T \Sigma^{-1}(\bf{x}-\mu) \right)}
$$

::: {.small}
```{python}
def mv_norm(x, μ, Σ):
  x = np.asarray(x)
  μ = np.asarray(μ)
  Σ = np.asarray(Σ)
  
  return ( np.linalg.det(2*np.pi*Σ)**(-0.5) * 
           np.exp(-0.5 * (x - μ).T @ np.linalg.solve(Σ, (x-μ)) ) )
```
:::

. . .

:::: {.columns .small}
::: {.column width='50%'}
```{python}
norm_pdf(0,0,1)
```
```{python}
mv_norm([0], [0], [[1]])
```
:::

::: {.column width='50%'}
```{python}
mv_norm([0,0], [0,0], [[1,0],[0,1]])
```
```{python}
mv_norm([0,0,0], [0,0,0], 
        [[1,0,0],[0,1,0],[0,0,1]])
```
:::
::::

## 2d & 3d numerical integration

These are supported by `dblquad()` and `tplquad()` respectively (see `nquad()` for higher dimensions).

::: {.small}
```{python}
#| cache: true
from scipy.integrate import dblquad, tplquad
```

```{python}
#| cache: true
dblquad(lambda y, x: mv_norm([x,y], [0,0], np.identity(2)),
        a=-np.inf, b=np.inf,
        gfun=lambda x: -np.inf,   hfun=lambda x: np.inf)
```
:::

. . .

::: {.small}
```{python}
#| cache: true
tplquad(lambda z, y, x: mv_norm([x,y,z], [0,0,0], np.identity(3)),
        a=0, b=np.inf,
        gfun=lambda x:   0, hfun=lambda x:   np.inf,
        qfun=lambda x,y: 0, rfun=lambda x,y: np.inf)
```
:::



# Example 3 <br/> (Very) Basic optimization

## Scalar function minimization

:::: {.columns .xsmall}
::: {.column width='50%'}
```{python}
def f(x):
    return x**4 + 3*(x-2)**3 - 15*(x)**2 + 1
```

```{python}
#| echo: false
plt.figure(figsize=(5, 3.5))
x = np.linspace(-8, 5, 100)
plt.plot(x, f(x))
```
:::

::: {.column width='50%' .fragment}
```{python}
from scipy.optimize import minimize_scalar
minimize_scalar(f)
```
:::
::::


## Results

::: {.xsmall}
```{python}
res = minimize_scalar(f)
```
```{python}
type(res)
```
```{python}
dir(res)
```
:::

::: {.columns .xsmall}
::: {.column}
```{python}
res.fun
```
```{python}
print(res.message)
```
```{python}
res.nfev
```
:::
::: {.column}
```{python}
res.nit
```
```{python}
res.success
```
```{python}
res.x
```
:::
:::


## More details

::: {.xsmall}
```{python}
from scipy.optimize import show_options
show_options(solver="minimize_scalar")
```
:::


## Local minima

:::: {.columns .small}
::: {.column width='50%'}
```{python}
def f(x):
  return -np.sinc(x-5)
```


```{python}
#| echo: false
plt.figure(figsize=(5, 3.5))
x = np.linspace(-20, 20, 500)
p = plt.plot(x, f(x));
plt.show()
```
:::

::: {.column width='50%' .fragment}
```{python}
res = minimize_scalar(f); res
```


```{python}
#| echo: false
plt.figure(figsize=(3, 1.75))
x = np.linspace(-20, 20, 500)
p = plt.plot(x, f(x));
plt.axvline(res.x, c='red')
plt.show()
```
:::
::::


## Random starts

::: {.xsmall}
```{python}
#| output-location: column
rng = np.random.default_rng(seed=1234)

lower = rng.uniform(-20, 20, 100)
upper = lower + 1

sols = [minimize_scalar(f, bracket=(l,u)) 
        for l,u in zip(lower, upper)]
funs = [sol.fun for sol in sols]

best = sols[np.argmin(funs)]
best
```
:::

```{python}
#| echo: false
#| fig-align: center
plt.figure(figsize=(3, 2))
p = plt.plot(x, f(x));
plt.axvline(best.x, c='red')
plt.show()
```



# Example 4 <br/> Statistics

## Distributions 

Implements classes for most continuous and discrete distributions,

* `rvs` -  Random Variates

* `pdf` -  Probability Density Function

* `cdf` -  Cumulative Distribution Function

* `sf` -  Survival Function (1-CDF)

* `ppf` -  Percent Point Function (Inverse of CDF)

* `isf` -  Inverse Survival Function (Inverse of SF)

* `stats` -  Return mean, variance, (Fisher’s) skew, or (Fisher’s) kurtosis

* `moment` -  non-central moments of the distribution


## Basic usage

::: {.xsmall}
```{python}
from scipy.stats import norm, gamma, binom, uniform
```
:::

. . .

::: {.xsmall}
```{python}
norm().rvs(size=5)
```
:::

. . .

::: {.xsmall}
```{python}
uniform.pdf([0,0.5,1,2])
```
:::

. . .

::: {.xsmall}
```{python}
binom.mean(n=10, p=0.25)
```
```{python}
binom.median(n=10, p=0.25)
```
:::

. . .

::: {.xsmall}
```{python}
norm().stats()
```
```{python}
gamma(a=1,scale=1).stats(moments="mvsk")
```

:::


## Freezing

Model parameters can be passed to any of the methods directly, or a distribution can be constructed using a specific set of parameters, which is known as freezing.

:::: {.columns .xsmall}
::: {.column width='50%'}
```{python}
norm_rv = norm(loc=-1, scale=3)
norm_rv.median()
```

```{python}
unif_rv = uniform(loc=-1, scale=2)
unif_rv.cdf([-2,-1,0,1,2])
```
```{python}
unif_rv.rvs(5)
```
:::

::: {.column width='50%' .fragment}
```{python}
g = gamma(a=2, loc=0, scale=1.2)

plt.figure(figsize=(3, 2))
x = np.linspace(0, 10, 100)
plt.plot(x, g.pdf(x), "k-")
plt.axvline(x=g.mean(), c="r")
plt.axvline(x=g.median(), c="b")
```
:::
::::


## MLE

Maximum likelihood estimation is possible via the `fit()` method,

::: {.small}
```{python}
x = norm.rvs(loc=2.5, scale=2, size=1000, random_state=1234)
```
```{python}
norm.fit(x)
```
```{python}
norm.fit(x, loc=2.5) # provide a guess for the parameter
```
:::

. . .

::: {.small}
```{python}
x = gamma.rvs(a=2.5, size=1000)
gamma.fit(x) # shape, loc, scale
```
```{python}
y = gamma.rvs(a=2.5, loc=-1, scale=2, size=1000)
gamma.fit(y) # shape, loc, scale
```
:::


# Example 5 <br/> Special Functions

## scipy.special

Provides implementations of many special mathematical functions commonly used in statistics, physics, and engineering.

::: {.small}
| Function | Description |
|:---------|:------------|
| `gamma`, `gammaln` | Gamma function and its log |
| `beta`, `betaln` | Beta function and its log |
| `factorial`, `comb`, `perm` | Combinatorial functions |
| `erf`, `erfc` | Error function and complement |
| `expit`, `logit` | Logistic and inverse logistic |
| `softmax`, `log_softmax` | Softmax and log-softmax |
| `digamma`, `polygamma` | Digamma and polygamma functions |
| `bessel*` | Bessel functions (many variants) |
:::


## Gamma and Beta functions

::: {.small}
```{python}
from scipy.special import gamma, gammaln, beta, betaln
```
:::

:::: {.columns .small}
::: {.column width='50%'}

```{python}
gamma(5)  # (n-1)! for integers
```
```{python}
gamma(0.5)  # sqrt(pi)
```
```{python}
np.sqrt(np.pi)
```
:::

::: {.column width='50%' .fragment}
```{python}
gammaln(100)  # log(gamma(100))
```
```{python}
beta(2, 3)  # B(a,b) = gamma(a)*gamma(b)/gamma(a+b)
```
```{python}
gamma(2) * gamma(3) / gamma(5)
```
:::
::::


## Combinatorial functions

::: {.small}
```{python}
from scipy.special import factorial, comb, perm
```
:::

:::: {.columns .small}
::: {.column width='50%'}
```{python}
factorial(5)
```
```{python}
factorial(np.arange(6))
```
:::

::: {.column width='50%' .fragment}
```{python}
comb(10, 3)  # 10 choose 3
```
```{python}
perm(10, 3)  # 10 permute 3
```
:::
::::


## Error function

The error function $\text{erf}(x) = \frac{2}{\sqrt{\pi}} \int_0^x e^{-t^2} dt$,

::: {.small}
```{python}
from scipy.special import erf, erfc
```
:::

:::: {.small}
```{python}
erf(0)
```
```{python}
erf(np.inf)
```
```{python}
erfc(0)  # 1 - erf(x)
```
:::



## Logistic functions

::: {.small}
```{python}
from scipy.special import expit, logit, softmax
```
:::

:::: {.columns .small}
::: {.column width='50%'}
```{python}
expit(0)  # 1 / (1 + exp(-x))
```
```{python}
expit([-np.inf, 0, np.inf])
```
```{python}
logit(0.5)  # log(p / (1-p))
```
```{python}
logit([0.1, 0.5, 0.9])
```
:::

::: {.column width='50%' .fragment}
```{python}
softmax([1, 2, 3])
```
```{python}
softmax([1, 2, 3]).sum()
```
```{python}
softmax([0, 0, 0])
```
:::
::::


# Example 6 <br/> Linear Algebra

## NumPy vs SciPy linalg

Both `numpy.linalg` and `scipy.linalg` provide linear algebra routines, but SciPy's version is more comprehensive.

::: {.small}
| Feature | `numpy.linalg` | `scipy.linalg` |
|:--------|:---------------|:---------------|
| Basic operations | `inv`, `solve`, `det`, `eig` | All of NumPy's + more |
| Decompositions | SVD, QR, Cholesky | + LU, Schur, Hessenberg, polar |
| Matrix functions | Limited | `expm`, `logm`, `sqrtm`, `funm` |
| Specialized solvers | No | Banded, triangular, symmetric |
| LAPACK access | Partial | Full access via low-level routines |
:::


## Basic operations comparison

::: {.small}
```{python}
import scipy.linalg
```

```{python}
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
```
:::

:::: {.columns .small}
::: {.column width='50%'}
**NumPy**
```{python}
np.linalg.solve(A, b)
```
```{python}
np.linalg.inv(A)
```
:::

::: {.column width='50%'}
**SciPy**
```{python}
scipy.linalg.solve(A, b)
```
```{python}
scipy.linalg.inv(A)
```
:::
::::


## SciPy-only features

:::: {.columns .small}
::: {.column width='50%'}
LU Decomposition
```{python}
P, L, U = scipy.linalg.lu(A)
```
```{python}
L
```
```{python}
U
```
:::

::: {.column width='50%' .fragment}
Matrix exponential
```{python}
scipy.linalg.expm(A)
```
```{python}
scipy.linalg.logm(
  scipy.linalg.expm(A)
)
```
:::
::::


## Dense vs Sparse matrices

For matrices with many zero entries, sparse representations are more memory-efficient and can be much faster.

::: {.small}
```{python}
from scipy import sparse
```
:::

:::: {.columns .small}
::: {.column width='50%'}
Dense (stores all elements)
```{python}
dense = np.array([
    [1, 0, 0, 0],
    [0, 2, 0, 0],
    [0, 0, 3, 0],
    [0, 0, 0, 4]
])
dense.nbytes
```
:::

::: {.column width='50%' .fragment}
Sparse (stores only non-zeros)
```{python}
sp = sparse.csr_matrix(dense)
sp
```
```{python}
sp.data
```
:::
::::


## Sparse matrix formats

| Format | Name           | Best for                       |
|:-------|:---------------|:-------------------------------|
| `csr_matrix` | Compressed Sparse Row | Row slicing, matrix-vector products |
| `csc_matrix` | Compressed Sparse Column | Column slicing, arithmetic |
| `coo_matrix` | Coordinate | Building sparse matrices incrementally |
| `dia_matrix` | Diagonal | Diagonal/banded matrices |
| `lil_matrix` | List of Lists | Building matrices, row-based modifications |


## Creating sparse matrices

:::: {.columns .xsmall}
::: {.column width='50%'}
```{python}
row = [0, 1, 2, 2]
col = [0, 1, 0, 2]
data = [1, 2, 3, 4]
sp = sparse.coo_matrix(
  (data, (row, col)), shape=(3, 3)
)
sp.toarray()
```
:::

::: {.column width='50%'}
```{python}
sparse.eye(4, format="csr").toarray()
```
```{python}
sparse.random(3, 3, density=0.3).toarray()
```
:::
::::

::: {.xsmall}
```{python}
sparse.diags([1., 2., 3., 4.]).toarray()
```
:::


## Sparse linear algebra

`scipy.sparse.linalg` provides solvers optimized for sparse matrices.

::: {.small}
```{python}
from scipy.sparse.linalg import spsolve, eigs
```
```{python}
n = 1000
diagonals = [np.ones(n-1), -2*np.ones(n), np.ones(n-1)]
A_sparse = sparse.diags(diagonals, [-1, 0, 1], format="csr")
b = np.ones(n)
```


```{python}
x = spsolve(A_sparse, b)
x[:5]
```

```{python}
vals, vecs = eigs(A_sparse, k=3)
vals
```
:::


## When to use sparse?

General rule - use sparse when *density < 10%* and matrix is large.

```{python}
#| echo: false
#| fig-align: center
sizes = [100, 500, 1000, 2000]
dense_mem = [8 * n**2 / 1e6 for n in sizes]
sparse_mem = [8 * 0.01 * n**2 * 3 / 1e6 for n in sizes]  # ~1% density, CSR overhead

plt.figure(figsize=(5, 3))
plt.plot(sizes, dense_mem, "-o", label="Dense")
plt.plot(sizes, sparse_mem, "-s", label="Sparse (1% density)")
plt.xlabel("Matrix dimension (n x n)")
plt.ylabel("Memory (MB)")
plt.legend()
plt.title("Memory usage: Dense vs Sparse")
plt.show()
```
